/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { HasherAbi, HasherAbiInterface } from "../HasherAbi";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "_c",
        type: "uint8",
      },
      {
        name: "_salt",
        type: "uint256",
      },
    ],
    name: "hash",
    outputs: [
      {
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class HasherAbi__factory {
  static readonly abi = _abi;
  static createInterface(): HasherAbiInterface {
    return new utils.Interface(_abi) as HasherAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HasherAbi {
    return new Contract(address, _abi, signerOrProvider) as HasherAbi;
  }
}
